apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp-deployment
  labels:
    app: mongo-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
      - name: mongo-exp
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME  
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mobgo-root-username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER    
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: database-url
      